### EXPORT ORDER

POST {{API_URL}}/exports HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3ODAxMjYyOTN9.J1PRaMbzRLRxrXUlCMiuUfoTd7ovOyS2X8cWcVjIufg

{
  "endDate": "2020-01-01T06:15:00Z",
  "startDate": "2020-01-01T06:15:00Z"
}


### GET EXPORT STATUS

GET {{API_URL}}/exports/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3ODAxMjYyOTN9.J1PRaMbzRLRxrXUlCMiuUfoTd7ovOyS2X8cWcVjIufg
